### ISSUE TITLE
Issues with MPI-enabled corr_to_clarray()

### ISSUE THREAD

**Issue by sjforeman** [radiocosmology/cora#62]
https://github.com/radiocosmology/cora/pull/61 introduced modifications to enable certain steps of the LSS-generation pipeline to use MPI, but @shabbir137 and @PanChristeas have encountered issues with `GenerateLSS` failing to complete in the latest version. The last log message is `"Generating C_l(x, x')"`, which seems to indicate that the issue is within `corrfunc.corr_to_clarray`. 

Here is an example of a `GenerateLSS` config block that takes longer than the corresponding serial time on one node, on cedar:
```yaml
time: 30
system: cedar
nodes: 8
ompnum: 24
pernode: 2
mem: 192000M

.................

type: cora.signal.lss.GenerateInitialLSS
requires: corr
out: lss
params:
  frequencies:
    start: 707.8125
    stop: 647.8125
    num: 128
    endpoint: false
  nside: 512
  save: true
  output_name: lss.h5
```
And here is a table of runtimes compiled by @shabbir137:

![Image](https://github.com/user-attachments/assets/1bec067c-821f-42ee-82fc-6f317f9ce40f)

Things are worse with `nside=1024` and higher, which were the original motivation for parallelizing this part of the pipeline. It seems that the MPI-enabled version is still not scaling sufficiently steeply to be useful for CHIME/CHORD simulation pipelines.
